### ISSUE TITLE
Invalid inputs given to generate an instance of 'OsConfigurationFileListAllOf'[Backend: INTERSIGHT-10157]

### ISSUE THREAD

**Issue by sfloresk** [CiscoDevNet/intersight-python#16]
When retrieving the list of config files to install an operating system, an schema exception is raised:

Code:
```python
api_instance = os_api.OsApi(api_client)
# Fetching the result with the configuration file.
api_response = api_instance.get_os_configuration_file_list()
return api_response
```

Traceback:
```
Traceback (most recent call last):
  File "***", line 326, in fetch_os_config_file
    api_response = api_instance.get_os_configuration_file_list()
  File ".penv/lib/python3.8/site-packages/intersight/api_client.py", line 779, in __call__
    return self.callable(self, *args, **kwargs)
  File ".penv/lib/python3.8/site-packages/intersight/api/os_api.py", line 1784, in __get_os_configuration_file_list
    return self.call_with_http_info(**kwargs)
  File ".penv/lib/python3.8/site-packages/intersight/api_client.py", line 841, in call_with_http_info
    return self.api_client.call_api(
  File ".penv/lib/python3.8/site-packages/intersight/api_client.py", line 409, in call_api
    return self.__call_api(resource_path, method,
  File ".penv/lib/python3.8/site-packages/intersight/api_client.py", line 224, in __call_api
    return_data = self.deserialize(
  File ".penv/lib/python3.8/site-packages/intersight/api_client.py", line 325, in deserialize
    deserialized_data = validate_and_convert_types(
  File ".penv/lib/python3.8/site-packages/intersight/model_utils.py", line 1395, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File ".penv/lib/python3.8/site-packages/intersight/model_utils.py", line 1291, in attempt_convert_item
    raise conversion_exc
  File ".penv/lib/python3.8/site-packages/intersight/model_utils.py", line 1282, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File ".penv/lib/python3.8/site-packages/intersight/model_utils.py", line 1202, in deserialize_model
    return model_class(**kw_args)
  File ".penv/lib/python3.8/site-packages/intersight/model_utils.py", line 284, in __new__
    new_inst.__init__(*args, **kwargs)
  File ".penv/lib/python3.8/site-packages/intersight/model_utils.py", line 1567, in wrapped_init
    return fn(self, *args, **kwargs)
  File ".penv/lib/python3.8/site-packages/intersight/model/os_configuration_file_list.py", line 201, in __init__
    composed_info = validate_get_composed_info(
  File ".penv/lib/python3.8/site-packages/intersight/model_utils.py", line 1847, in validate_get_composed_info
    allof_instances = get_allof_instances(self, model_args, constant_args)
  File ".penv/lib/python3.8/site-packages/intersight/model_utils.py", line 1602, in get_allof_instances
    raise ApiValueError(
intersight.exceptions.ApiValueError: Invalid inputs given to generate an instance of 'OsConfigurationFileListAllOf'. The input data was invalid for the allOf schema 'OsConfigurationFileListAllOf' in the composed schema 'OsConfigurationFileList'. Error=Invalid inputs given to generate an instance of 'OsConfigurationFileAllOf'. The input data was invalid for the allOf schema 'OsConfigurationFileAllOf' in the composed schema 'OsConfigurationFile'. Error=Invalid inputs given to generate an instance of 'OsPlaceHolderAllOf'. The input data was invalid for the allOf schema 'OsPlaceHolderAllOf' in the composed schema 'OsPlaceHolder'. Error=Invalid inputs given to generate an instance of 'WorkflowBaseDataType'. The input data was invalid for the allOf schema 'WorkflowBaseDataType' in the composed schema 'WorkflowPrimitiveDataType'. Error=Invalid inputs given to generate an instance of 'WorkflowBaseDataTypeAllOf'. The input data was invalid for the allOf schema 'WorkflowBaseDataTypeAllOf' in the composed schema 'WorkflowBaseDataType'. Error=Invalid value for `label`, must match regular expression `^[a-zA-Z0-9]+[\sa-zA-Z0-9_\'.:-]{1,92}$`
python-BaseException
```

**Comment by 3191110276** [comment]
I tried these request as well, and I am facing problems as well:

api_instance = os_api.OsApi(api_client)
x = api_instance.get_os_configuration_file_list()

Traceback (most recent call last):
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1599, in get_allof_instances
    allof_instance = allof_class(**kwargs)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1567, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model/workflow_base_data_type_all_of.py", line 230, in __init__
    setattr(self, var_name, var_value)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 168, in __setattr__
    self[attr] = value
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 353, in __setitem__
    self.set_attribute(name, value)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 150, in set_attribute
    check_validations(
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 868, in check_validations
    raise ApiValueError(err_msg)
intersight.exceptions.ApiValueError: Invalid value for `name`, must match regular expression `^[a-zA-Z0-9]+([a-zA-Z0-9-_]*[a-zA-Z0-9])*$`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1599, in get_allof_instances
    allof_instance = allof_class(**kwargs)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1567, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model/workflow_base_data_type.py", line 266, in __init__
    composed_info = validate_get_composed_info(
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1847, in validate_get_composed_info
    allof_instances = get_allof_instances(self, model_args, constant_args)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1602, in get_allof_instances
    raise ApiValueError(
intersight.exceptions.ApiValueError: Invalid inputs given to generate an instance of 'WorkflowBaseDataTypeAllOf'. The input data was invalid for the allOf schema 'WorkflowBaseDataTypeAllOf' in the composed schema 'WorkflowBaseDataType'. Error=Invalid value for `name`, must match regular expression `^[a-zA-Z0-9]+([a-zA-Z0-9-_]*[a-zA-Z0-9])*$`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1599, in get_allof_instances
    allof_instance = allof_class(**kwargs)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1567, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model/os_place_holder_all_of.py", line 196, in __init__
    setattr(self, var_name, var_value)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 168, in __setattr__
    self[attr] = value
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 353, in __setitem__
    self.set_attribute(name, value)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 140, in set_attribute
    value = validate_and_convert_types(
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1395, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1291, in attempt_convert_item
    raise conversion_exc
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1282, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1202, in deserialize_model
    return model_class(**kw_args)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1567, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model/workflow_primitive_data_type.py", line 249, in __init__
    composed_info = validate_get_composed_info(
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1847, in validate_get_composed_info
    allof_instances = get_allof_instances(self, model_args, constant_args)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1602, in get_allof_instances
    raise ApiValueError(
intersight.exceptions.ApiValueError: Invalid inputs given to generate an instance of 'WorkflowBaseDataType'. The input data was invalid for the allOf schema 'WorkflowBaseDataType' in the composed schema 'WorkflowPrimitiveDataType'. Error=Invalid inputs given to generate an instance of 'WorkflowBaseDataTypeAllOf'. The input data was invalid for the allOf schema 'WorkflowBaseDataTypeAllOf' in the composed schema 'WorkflowBaseDataType'. Error=Invalid value for `name`, must match regular expression `^[a-zA-Z0-9]+([a-zA-Z0-9-_]*[a-zA-Z0-9])*$`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1599, in get_allof_instances
    allof_instance = allof_class(**kwargs)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1567, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model/os_configuration_file_all_of.py", line 221, in __init__
    setattr(self, var_name, var_value)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 168, in __setattr__
    self[attr] = value
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 353, in __setitem__
    self.set_attribute(name, value)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 140, in set_attribute
    value = validate_and_convert_types(
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1445, in validate_and_convert_types
    input_value[index] = validate_and_convert_types(
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1395, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1291, in attempt_convert_item
    raise conversion_exc
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1282, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1202, in deserialize_model
    return model_class(**kw_args)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1567, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model/os_place_holder.py", line 216, in __init__
    composed_info = validate_get_composed_info(
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1847, in validate_get_composed_info
    allof_instances = get_allof_instances(self, model_args, constant_args)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1602, in get_allof_instances
    raise ApiValueError(
intersight.exceptions.ApiValueError: Invalid inputs given to generate an instance of 'OsPlaceHolderAllOf'. The input data was invalid for the allOf schema 'OsPlaceHolderAllOf' in the composed schema 'OsPlaceHolder'. Error=Invalid inputs given to generate an instance of 'WorkflowBaseDataType'. The input data was invalid for the allOf schema 'WorkflowBaseDataType' in the composed schema 'WorkflowPrimitiveDataType'. Error=Invalid inputs given to generate an instance of 'WorkflowBaseDataTypeAllOf'. The input data was invalid for the allOf schema 'WorkflowBaseDataTypeAllOf' in the composed schema 'WorkflowBaseDataType'. Error=Invalid value for `name`, must match regular expression `^[a-zA-Z0-9]+([a-zA-Z0-9-_]*[a-zA-Z0-9])*$`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1599, in get_allof_instances
    allof_instance = allof_class(**kwargs)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1567, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model/os_configuration_file_list_all_of.py", line 175, in __init__
    setattr(self, var_name, var_value)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 168, in __setattr__
    self[attr] = value
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 353, in __setitem__
    self.set_attribute(name, value)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 140, in set_attribute
    value = validate_and_convert_types(
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1445, in validate_and_convert_types
    input_value[index] = validate_and_convert_types(
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1395, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1291, in attempt_convert_item
    raise conversion_exc
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1282, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1202, in deserialize_model
    return model_class(**kw_args)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1567, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model/os_configuration_file.py", line 288, in __init__
    composed_info = validate_get_composed_info(
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1847, in validate_get_composed_info
    allof_instances = get_allof_instances(self, model_args, constant_args)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1602, in get_allof_instances
    raise ApiValueError(
intersight.exceptions.ApiValueError: Invalid inputs given to generate an instance of 'OsConfigurationFileAllOf'. The input data was invalid for the allOf schema 'OsConfigurationFileAllOf' in the composed schema 'OsConfigurationFile'. Error=Invalid inputs given to generate an instance of 'OsPlaceHolderAllOf'. The input data was invalid for the allOf schema 'OsPlaceHolderAllOf' in the composed schema 'OsPlaceHolder'. Error=Invalid inputs given to generate an instance of 'WorkflowBaseDataType'. The input data was invalid for the allOf schema 'WorkflowBaseDataType' in the composed schema 'WorkflowPrimitiveDataType'. Error=Invalid inputs given to generate an instance of 'WorkflowBaseDataTypeAllOf'. The input data was invalid for the allOf schema 'WorkflowBaseDataTypeAllOf' in the composed schema 'WorkflowBaseDataType'. Error=Invalid value for `name`, must match regular expression `^[a-zA-Z0-9]+([a-zA-Z0-9-_]*[a-zA-Z0-9])*$`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 49, in <module>
    x = api_instance.get_os_configuration_file_list()#**kwargs)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/api_client.py", line 779, in __call__
    return self.callable(self, *args, **kwargs)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/api/os_api.py", line 1784, in __get_os_configuration_file_list
    return self.call_with_http_info(**kwargs)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/api_client.py", line 841, in call_with_http_info
    return self.api_client.call_api(
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/api_client.py", line 409, in call_api
    return self.__call_api(resource_path, method,
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/api_client.py", line 224, in __call_api
    return_data = self.deserialize(
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/api_client.py", line 325, in deserialize
    deserialized_data = validate_and_convert_types(
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1395, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1291, in attempt_convert_item
    raise conversion_exc
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1282, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1202, in deserialize_model
    return model_class(**kw_args)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 284, in __new__
    new_inst.__init__(*args, **kwargs)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1567, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model/os_configuration_file_list.py", line 201, in __init__
    composed_info = validate_get_composed_info(
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1847, in validate_get_composed_info
    allof_instances = get_allof_instances(self, model_args, constant_args)
  File "/home/mimaurer/.local/lib/python3.8/site-packages/intersight/model_utils.py", line 1602, in get_allof_instances
    raise ApiValueError(
intersight.exceptions.ApiValueError: Invalid inputs given to generate an instance of 'OsConfigurationFileListAllOf'. The input data was invalid for the allOf schema 'OsConfigurationFileListAllOf' in the composed schema 'OsConfigurationFileList'. Error=Invalid inputs given to generate an instance of 'OsConfigurationFileAllOf'. The input data was invalid for the allOf schema 'OsConfigurationFileAllOf' in the composed schema 'OsConfigurationFile'. Error=Invalid inputs given to generate an instance of 'OsPlaceHolderAllOf'. The input data was invalid for the allOf schema 'OsPlaceHolderAllOf' in the composed schema 'OsPlaceHolder'. Error=Invalid inputs given to generate an instance of 'WorkflowBaseDataType'. The input data was invalid for the allOf schema 'WorkflowBaseDataType' in the composed schema 'WorkflowPrimitiveDataType'. Error=Invalid inputs given to generate an instance of 'WorkflowBaseDataTypeAllOf'. The input data was invalid for the allOf schema 'WorkflowBaseDataTypeAllOf' in the composed schema 'WorkflowBaseDataType'. Error=Invalid value for `name`, must match regular expression `^[a-zA-Z0-9]+([a-zA-Z0-9-_]*[a-zA-Z0-9])*$`

**Comment by the-akhil-nair** [comment]
With latest version of python SDK (v1.0.11.17956), the issue is not reproducible. Please try with latest version of python SDK and let us know.
